base:
  charset: 'utf-8'
  sqlpath: './script/crawler-create.sql'

database:
  dbtype: 'sqlite'
  dbpath: './data/crawler.db'
  
  # dbtype: 'mysql'
  # host: '127.0.0.1'
  # port: 3306
  # username: 'stock'
  # password: "<%= ENV['DB_PASS'] %>"
  # dbname: 'stock'
  # encoding: 'utf8'

